-- Editable services: one row per fixed service, seeded verbatim from
-- static/services.ts (this file was GENERATED — do not hand-edit seed text).
-- JSON columns hold the fixed-shape lists; images seed with key '' so the
-- public pages keep their placeholder frames until photos are uploaded.
CREATE TABLE services (
	slug TEXT PRIMARY KEY,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	tagline TEXT NOT NULL,
	overview TEXT NOT NULL,
	when_you_need_it TEXT NOT NULL,
	specs TEXT NOT NULL,
	process TEXT NOT NULL,
	compliance_tags TEXT NOT NULL,
	faq_ids TEXT NOT NULL,
	images TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

INSERT INTO services (slug, title, body, tagline, overview, when_you_need_it, specs, process, compliance_tags, faq_ids, images, updated_at) VALUES
	('class-a-hoarding', 'Class A hoarding', 'Fence-type hoarding at ground level — solid, plumb and lockable. Steel-framed ply or panel systems with dust control, sightline screening and pedestrian doors where the site needs them.', 'Ground-level hoarding that stands straight and locks up tight.', 'Class A is the fence-type hoarding that separates your site from the footpath — steel-framed, ply or panel-clad, and stood plumb the first time. It carries dust screening, sightline control and pedestrian doors wherever the site needs foot traffic through, and it''s built to survive the wind study, not just pass the first inspection.', 'If your work is happening at ground level and the public needs to be kept out — demolition, excavation, ground-floor fit-out — Class A is the minimum council requirement. It''s also the hoarding you''ll stand first on almost every job, ahead of any Class B gantry that goes up once work moves above the footpath.', '[{"label":"Frame","detail":"Steel-framed panel or ply cladding, engineered to the site wind zone"},{"label":"Height","detail":"Standard 1.8–2.4m, engineered higher on request"},{"label":"Access","detail":"Lockable pedestrian and vehicle gates positioned to the site plan"},{"label":"Finish","detail":"Dust screening, sightline mesh or solid infill, ready for graphics"}]', '[{"step":"Site walk","detail":"We measure the frontage and confirm the footpath situation on-site."},{"step":"Drawings & permit","detail":"Engineered layout drawn, certified, and lodged with council."},{"step":"Install","detail":"Panels stood, braced and locked off — typically within days of permit approval."},{"step":"Dismantle","detail":"Struck on the program date, footpath handed back clean."}]', '["AS 4687 certified","SafeWork NSW compliant","Licensed installers"]', '["council-approval","class-a-vs-class-b","install-speed"]', '[{"key":"","alt":"Class A hoarding installed on site"},{"key":"","alt":"Class A hoarding gate and signage detail"}]', '2026-08-20T00:00:00.000Z'),
	('class-b-hoarding', 'Class B hoarding', 'Overhead gantry protection where work happens above a footpath. Engineered decks rated to the drawings, under-awning lighting, and certification the council accepts.', 'Overhead protection engineered for the load, not just the look.', 'Class B is the engineered gantry deck that goes up when work happens above a footpath you''re keeping open — it catches falling material, carries under-awning lighting, and comes with the load documentation your certifier will actually accept. Every deck is drawn to the job''s specific loads, not pulled off a generic template.', 'Required wherever work is happening above a public footpath that stays trafficable — demolition above street level, facade work, crane lifts over a live footpath. As a rule of thumb NSW councils trigger a Class B deck once a building adjoining the footpath is 7.5m or taller and sits within 3.5m of the street alignment. If pedestrians are walking under the work, council will ask for a Class B deck and the engineering to back it.', '[{"label":"Deck","detail":"Engineered overhead deck rated to the specific load case for your job"},{"label":"Lighting","detail":"Under-awning lighting to the standard required for a trafficable footpath"},{"label":"Interface","detail":"Ties into scaffold, existing structure or ground-level Class A hoarding"},{"label":"Certification","detail":"Signed structural documentation your certifier can lodge immediately"}]', '[{"step":"Load case & drawings","detail":"Our engineers assess the works above and draw the deck to the AS/NZS 1170 load cases."},{"step":"Council lodgement","detail":"Structural certification and permit lodged before install."},{"step":"Install","detail":"Deck erected and tied in, lighting commissioned before the footpath reopens."},{"step":"Inspection & handover","detail":"Signed off and re-certified at six-monthly intervals while it stays up."}]', '["AS/NZS 1170 engineered","Engineer-signed load case","SafeWork NSW compliant"]', '["class-a-vs-class-b","certification","install-speed"]', '[{"key":"","alt":"Class B overhead gantry deck"},{"key":"","alt":"Class B under-awning lighting"}]', '2026-08-20T00:00:00.000Z'),
	('design-certification', 'Design & certification', 'Every hoarding drawn and signed to AS 4687 by our engineers. Load cases, tie-downs and documentation your certifier accepts the first time.', 'Every hoarding signed off before it''s stood, not after.', 'Every hoarding we put up is drawn and engineered in-house to AS 4687 — load cases, tie-downs, wind ratings, and the documentation your certifier or principal contractor actually asks for. We also take on design-and-certify work for hoardings other crews are installing, where you need the engineering but already have the labour.', 'Any hoarding on public land needs certified drawings before a council will issue a permit. If your engineer is booked out, or you need certification fast-tracked against a program date, this is a standalone service — you don''t need to buy the install from us to get the paperwork.', '[{"label":"Scope","detail":"Load cases, tie-down details and general arrangement drawings"},{"label":"Standard","detail":"Designed and signed to AS 4687 by our engineers"},{"label":"Turnaround","detail":"Drawings issued fast enough to hold a permit deadline"},{"label":"Handover","detail":"Documentation supplied ready to lodge with your certifier or council"}]', '[{"step":"Brief","detail":"Send us the site plan and what''s going up — we scope the drawings needed."},{"step":"Engineering","detail":"Load cases and tie-downs calculated to the site''s specific conditions."},{"step":"Drawings issued","detail":"Signed drawings delivered ready to lodge."},{"step":"Support","detail":"We answer certifier or council queries on the drawings until it''s approved."}]', '["AS 4687 certified","Engineer-signed documentation"]', '["certification","class-a-vs-class-b"]', '[{"key":"","alt":"Certified hoarding drawing"},{"key":"","alt":"Engineering sign-off on site"}]', '2026-08-20T00:00:00.000Z'),
	('council-permits', 'Council permits', 'We draw it, certify it and lodge it — hoarding permits, footpath occupation and traffic control plans. You build; we handle the paperwork.', 'We draw it, certify it, lodge it — you keep building.', 'Hoarding permits, footpath occupation approvals and traffic control plans — we handle the whole council pathway so your program doesn''t stall waiting on paperwork. Drawings, certification and the application itself are prepared and lodged by us, with a single point of contact if the council comes back with questions.', 'Any hoarding standing on or over public land — a footpath, road reserve or laneway — needs a council permit before it goes up. If you''re managing the permit yourself and it''s holding up your start date, this is where we take it off your plate.', '[{"label":"Scope","detail":"Hoarding permit, footpath occupation and traffic control plan applications"},{"label":"Council liaison","detail":"We lodge and respond to council queries directly"},{"label":"Documentation","detail":"Certified drawings and insurance certificates included with the application"},{"label":"Timeline","detail":"Lodged as soon as drawings are signed — no waiting on us to start the clock"}]', '[{"step":"Site assessment","detail":"We confirm what approvals your specific footpath and site need."},{"step":"Application prepared","detail":"Drawings, certification and forms assembled for lodgement."},{"step":"Lodged with council","detail":"Application submitted and tracked until approved."},{"step":"Approval handed over","detail":"You get the permit; we''re ready to install the day it clears."}]', '["Council-ready documentation","AS 4687 certified"]', '["council-approval"]', '[{"key":"","alt":"Council permit documentation"},{"key":"","alt":"Permitted hoarding on public footpath"}]', '2026-08-20T00:00:00.000Z');
