-- Editable compliance-page content joins site_settings. Seeds equal the
-- page's current hardcoded copy (JSX &rsquo; entities carried as ’), so the
-- cutover is invisible. Image KEYS are not seeded — absent keys render the
-- placeholder frames. INSERT OR IGNORE keeps a partial remote apply safe.
INSERT OR IGNORE INTO site_settings (key, value, updated_at) VALUES
	('compliance.headline', 'Compliant is the minimum', '2026-08-20T00:00:00.000Z'),
	('compliance.intro', 'Every hoarding we put up is designed, certified and permitted before the first panel goes up. This is what that actually means — the standard we build to, the approvals council asks for, and what lands in your inbox when the job’s done.', '2026-08-20T00:00:00.000Z'),
	('compliance.standards_body', 'Class A fencing and hoardings are built to AS 4687, the Australian Standard for temporary fencing and hoardings. Class B overhead decks are a different animal — they’re engineered to AS/NZS 1170 load cases under the SafeWork NSW Overhead Protective Structures Code of Practice. Either way, the engineering is done from the first drawing, not retrofitted with paperwork once the structure’s already standing.', '2026-08-20T00:00:00.000Z'),
	('compliance.standards_cards', '[{"label":"Drawings","detail":"General arrangement drawings for the specific site and hoarding type"},{"label":"Load cases","detail":"Wind, live and dead loads calculated for the site''s actual conditions"},{"label":"Tie-downs","detail":"Footing and tie-down details engineered to the ground conditions on site"},{"label":"Sign-off","detail":"Signed and stamped by our structural engineer before the permit is lodged"}]', '2026-08-20T00:00:00.000Z'),
	('compliance.permits_body', 'Any hoarding standing on or over public land — a footpath, road reserve or laneway — needs council consent under section 138 of the Roads Act 1993 before it goes up. Three approvals usually travel together: the hoarding permit itself, footpath occupation where the hoarding or gantry extends over council land, and a traffic control plan wherever pedestrians or vehicles need to be managed around it. We prepare and lodge all three, and stay the point of contact if council comes back with questions.', '2026-08-20T00:00:00.000Z'),
	('compliance.safework_body', 'Every install runs under a Safe Work Method Statement to SafeWork NSW’s requirements, and every installer on our crew holds the licence the job calls for — high-risk construction work licensing included. That’s not a certificate kept in a drawer; it’s what the crew is actually working to on site.', '2026-08-20T00:00:00.000Z'),
	('compliance.insurance_body', 'We carry $20M public liability cover on every job, and can supply a certificate of currency before you need one — for your principal contractor agreement, your PC’s file, or your own insurer.', '2026-08-20T00:00:00.000Z'),
	('compliance.handover_body', 'Every job hands back the same paper trail — nothing you have to chase after the crew’s left site.', '2026-08-20T00:00:00.000Z'),
	('compliance.handover_cards', '[{"label":"Engineering drawings","detail":"Signed general arrangement and load case drawings"},{"label":"Permit approvals","detail":"Copies of the hoarding, footpath and traffic control approvals"},{"label":"Insurance certificate","detail":"Certificate of currency for our $20M public liability cover"},{"label":"Compliance sign-off","detail":"Written confirmation the install matches the certified drawings"}]', '2026-08-20T00:00:00.000Z'),
	('compliance.permit_image_alt', 'Approved hoarding permit signage on site', '2026-08-20T00:00:00.000Z'),
	('compliance.crew_image_alt', 'Pacific Hoardings crew on site in full PPE', '2026-08-20T00:00:00.000Z');
